sudo: false
env:
  global:
    # Anaconda token
    - secure: "US94SbyTKd1exnoQJnfuu6diMh673ek3N1flz7VRsKBywjVTImTjpSYNllmR6AEUtT1OiyVSMEWd90yjJ/DejNmcNnHXE8hbCHsWY196U66wXLJjeVgspW0QC5xPRryPDw8Mn0o735v4shAmMxuQ8CoYe/Hx40e7OfwiaSheDEKAFOyDnGPeJYNc+T0jnB31USSu36AHBwRYgRIOcNpQCY3nnG+Gn2w2zTeUXUmKgSw+LYQXISPyyJRIL695Lw6jjNoW0U3LcsTenLb1bK64M4CwTLR42hxtB0dOiyYgUVwVSsUGXZR6pqH1lKoR8b9ANuUF4HwQN35nJdlccd1g91FKU3s15KmsGIVdsBbwD+iPPZKGi2EwwRx1iR5dNCaiXga+3uyZcpKq31zoD6R5fzSi/igLqEVsyxYoJtBhPiuZKcNnqv0hiFqx8ETO173qJNj1lAJUYz2ChDsoHz2ffzX+EncHBFq38VvtkmYUOPJ7Zg7PDbImNYEjaTXzUe9sWjMO2zgitL3RYJIXCaKs/+RqCuLgLALbHrBBI8UXNiAWnW4npDQQU8zV/x35isBQk6OXkxu0BW9atr6d590uIpD/M7uOxogICaOtszXYAvteIyuasZu/Qs1RcYtDpZizQKd+zQx7a7e7L+iYz05z6ySnQEwVT3qJk9bRuaWU+rY="

language: generic

matrix:
  include:
    - os: linux
      env: PYTHON="2.7"

    - os: linux
      env: PYTHON="3.5"

    - os: linux
      env: PYTHON="3.6"

    - os: osx
      env: PYTHON="2.7"

    - os: osx
      env: PYTHON="3.5"

    - os: osx
      env: PYTHON="3.6"

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        rvm get stable;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda config --append channels conda-forge
    - if [[ -z "$TRAVIS_TAG" ]]; then
        sed -i -e "s/\${PYTHON}/"${PYTHON}"/" test-environment.yaml;
        conda env create -qf test-environment.yaml;
        source activate test-environment;
      else
        conda install -q conda-build anaconda-client;
      fi
      # Useful for debugging any issues with conda
    - conda info -a
    - conda list

# command to run tests
script:
  - set -e
  - if [[ -z "$TRAVIS_TAG" ]]; then
      python setup.py test;
      if [[ "$PYTHON" == "3.6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
        git checkout -- test-environment.yaml;
        python setup.py install;
      fi
    else
      conda build conda.recipe --python=${PYTHON};
      anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda/conda-bld/*/optionloop*.tar.bz2;
    fi
  - set +e

before_deploy:
  - conda install pandoc
  - pip install pypandoc

deploy:
  provider: pypi
  user: kyleniemeyer
  password:
    secure: "lyvc669aRaXUTVKSn494yxtjNGUFr3enqmE36EqFVIOwFhRy3WWf6SSBouarxtkIF5fHEqdgcxGbulBa4Cwq+cCbXcIX+vlNgJ3cbDziubG7pIInYn3VD4mpdh4HfL/H7a5cTeNK4y1jiGPHq32wIkgMBLeCdEcNfnKTvIHdFIU2cdjYzexsPqGZaS9rRqpAePrEoxes7tgxxF2xThcBUJy/oewr61NHw+NRoHHJVwLepil6BfMF/l4M3aim8vkagqSeVuBOyq9CLFj7Xl6c/TRjsPYh8OCGqZfDku9c0Q/Mny2clrfTU5PqA62Y7pJgHh1SHODrmNCuRXOtTiBbKgv1weCATwfTUljW9cFqzcg4vJzbBzqTAgNjtMbgO3rlc93OioM82FlbdyMMIU3xKy0LTqVP09r3oBpE4GHF75iisErcMYbDapUeXzV8w2XHVgvs5Gvg817wTGeSOwjeMbB59sQ7NId5GpedsGLfL50w3GTmtc+iMfn51LR4M6D4ximzVjo9K487+QBQpLGvvEJwUPr5x6ZjdUthOOpAXu/gM/LhSdFeaYVpwbDlOr9n62rznjOA87cBt2TsJVZAJOqMzuCH/ccIsNoIuP4W5EglEpSj2dYvQVa5467Hze8fsh3f3GBHNTDQL0/IVMs0q9Uq8Vnnb7T1jWUVN6poVYQ="
  on:
    tags: true
    condition: $TRAVIS_OS_NAME == "linux" && $PYTHON == "3.6"
  distributions: "sdist bdist_wheel"
  skip_upload_docs: true
